default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DB_HOST", "127.0.0.1") %>
  username: <%= ENV.fetch("DATABASE_USER", "rubylearning") %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  <% if Gem.win_platform? && ENV["APPDATA"] %>
  passfile: <%= File.join(ENV["APPDATA"], "postgresql", "pgpass.conf").to_json %>
  <% end %>

development:
  <<: *default
  database: rubylearning_development

test:
  <<: *default
  database: rubylearning_test

production: &deployed
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV["DATABASE_URL"] %>

review:
  <<: *deployed